### ISSUE TITLE
Cannot run program from another directory

### ISSUE THREAD

**Issue by toehold** [samadritakarmakar/GATE_calculator#1]
When calling the program from another directory, it issues this message: Cannot Find Diectory "Calc"
This is because it expects the program to be called from within its installation directory.

**Comment by samadritakarmakar** [comment]
Hi! Yes you are right about that issue.
I have made changes in the program. It now looks for the .html file in 3 places.
1. In the Current Directory then,
2. In the user's home Directory then finally,
3. Opens up the source website of the .html file.

I will upload the new code soon. As of now I have only tested this on Linux. Need to test this on Windows. After which I will Upload a new Release.
Please close the issue if you find the change satisfactory.
P.S. :- The typo has been corrected as well. ;)

**Comment by samadritakarmakar** [comment]
Tested on Linux and Windows. I have now uploaded a new releases with version tag of V1.1
Hope the new release will address the problems that you are facing.
I am closing the issue since I consider it solved.
